[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "https://1f78f357-11bb-48c6-852f-898b4b59f22f.railway.app/api/:splat"
  status = 200
